### ISSUE TITLE
Addon not loading when deployed to server

### ISSUE THREAD

**Issue by mikemartin** [aryehraber/statamic-splash#1]
When deploying to my server using the below Forge deploy script, the addon tags or fieldtype are not found. I suspect this might be a case sensitivity issue, as the addon works perfectly fine locally.

Here's my deploy script and error below:
```
cd /home/forge/thedepressionproject.mike-martin.ca
git pull origin master
composer install --no-interaction --prefer-dist --optimize-autoloader
```
https://flareapp.io/share/x7K3107R

**Comment by aryehraber** [comment]
Hey @mikemartin, thanks for bringing this to my attention. Admittedly I haven’t deployed this Addon to a server yet so perhaps something is wrong. 

Before I dive in, can you confirm that your published the vendor files on the server? Or perhaps you’ve committed those to your repo? They should live in `/public/vendor/aryehraber/statamic-splash/...`

**Comment by mikemartin** [comment]
Thanks @aryehraber,

Yes but it appears that the only vendor file on the server in `/public/vendor/aryehraber/statamic-splash/` is `js/splash-fieldtype.js`

Is that correct?

**Comment by aryehraber** [comment]
Yeah that’s correct, thanks for checking. 

I’ll give it a whirl on a server myself today and hopefully be able to debug and get back to you. Hold tight!

**Comment by aryehraber** [comment]
@mikemartin Just tested the installation process on a new {{S}} project and pushed to a test server; everything seems to work fine for me.

![2020-04-16 11 38 15](https://user-images.githubusercontent.com/5065331/79441353-68225c80-7fd7-11ea-8a5a-2636d1a8f526.gif)

Not really sure what's going wrong for you 🤔

Happy to help debug if you're willing to give temp. access to the project?

**Comment by mikemartin** [comment]
Hey @aryehraber,
I just invited you to the project. Let me know if you need anything else to debug.

**Comment by aryehraber** [comment]
@mikemartin Awesome, thanks! 

I _maaaaay_ need server access if I can't find anything obvious in the project repo, but will let you know if that's case, hopefully we can figure it out from here.

**Comment by mikemartin** [comment]
Solution was the equivalent of "turning it off and on again". Deleted the site and redeployed, works just fine.
