### ISSUE TITLE
Add lazysizes package to the build

### ISSUE THREAD

**Issue by jsblair9** [aryehraber/statamic-splash#11]
In the Statamic 3.2.28 update they changed how they do lazy loading for the `Thumbnail.vue` component 

https://github.com/statamic/cms/pull/4943/files

As a result, the grid of search result thumbnails no longer works for the addon since it is passing the data-src array

**Comment by aryehraber** [comment]
Thanks for the heads up! 

Makes sense that that could be the cause, a PR would be much appreciated 🙏

**Comment by jsblair9** [comment]
actually -- just need to add `lazysizes` package

**Comment by jsblair9** [comment]
since you don't have a published `package.json` or build or anything... probably easiest to let you add that in as a dependency!

**Comment by aryehraber** [comment]
Fixed in latest release, thanks again for bringing this to my attention!
