### ISSUE TITLE
The Image preview stopped working

### ISSUE THREAD

**Issue by bomshteyn** [aryehraber/statamic-splash#16]
This is what i see when i try to select an image to use
![Screen Shot 2022-02-03 at 2 50 21 PM](https://user-images.githubusercontent.com/4259699/152418948-4f2900d2-1df6-4516-96c3-e899a749a812.png)

I see the images request does come back successfully from unsplash API but the preview loading images stay as this forever

My environment:
PHP: 8.0
Laravel: 8.82.0
statamic : 3.2.32
statamic-splash: 1.0.6

**Comment by aryehraber** [comment]
Hi @bomshteyn, this should have been fixed in [`v1.0.6`](https://github.com/aryehraber/statamic-splash/releases/tag/v1.0.6)  due to a missing JS dependency (https://github.com/aryehraber/statamic-splash/issues/11). 

Could you try force-refreshing your browser and/or opening in an incognito window?

**Comment by bomshteyn** [comment]
Fixed this by running `npm run prod`
