### ISSUE TITLE
Download not triggered

### ISSUE THREAD

**Issue by danielduner** [aryehraber/statamic-splash#17]
The plugin does not seem to properly implement the Unsplash API Guidelines with regard to triggering downloads. When selecting an image, the plugin should send a request to the download endpoint.

Since no downloads are registered with the Unsplash API we are stuck in Demo mode (max 50 requests/h) and are unable to upgrade to Production mode (max 5000 requests/h)

See point 2 in this general guide:
https://help.unsplash.com/en/articles/2511245-unsplash-api-guidelines

And this page specifically discussing the download endpoint:
https://help.unsplash.com/en/articles/2511258-guideline-triggering-a-download

> When your application performs something similar to a download (like when a user chooses the image to include in a blog post, set as a header, etc.), you must send a request to the download endpoint returned under the photo.links.download_location  property.

**Comment by aryehraber** [comment]
Thanks for the info @danielduner, didn't know about this! 

I've you're able to create a PR to add this functionality, I'd be happy to review and merge. Otherwise, I'll try and find some time for this in the coming weeks.

**Comment by danielduner** [comment]
Thanks for the quick response! Unfortunately I'm not a php or Statamic dev, but I don't mind waiting a few weeks.

**Comment by aryehraber** [comment]
@danielduner Just released `v1.1.0` which pings Unsplash after selecting a photo as per their guidelines. Thanks again for pointing out this issue!

Please make sure to force publish the latest addon assets after updating:

```
php please vendor:publish --tag=splash --force
```
