### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by sebszocinski** [aryehraber/statamic-splash#2]
The UI for the search / image picker is a little broken (tested in both Chrome and Firefox):

![image](https://user-images.githubusercontent.com/5466694/83716590-79025c80-a66f-11ea-800e-598bde9d4557.png)

I can't seem to be able to select an image either, the cursor is a zoom icon?

Doesn't seem to be any console errors, so I can't help much more.

Using Statamic v3 Beta 28

**Comment by aryehraber** [comment]
Thanks @sebszocinski, I haven’t been keeping up with the latest beta releases, so probably something changed and needs updating in the addon. Will try fix asap!

**Comment by aryehraber** [comment]
Hey  @sebszocinski, that should be fixed now! 

You may need to manually remove the addon's assets (entire folder) from `public/vendor/...`, and rerun the installation:

```
php artisan vendor:publish --provider="AryehRaber\Splash\SplashServiceProvider"
```

Please reopen if you continue seeing this issue.
