### ISSUE TITLE
Suggestion: Streamline data saved to entry

### ISSUE THREAD

**Issue by sebszocinski** [aryehraber/statamic-splash#5]
I just noticed the addon is saving approx 130 lines of data to the entry for a single image... do you think we could trim this down? a lot of that information isn't needed.

Perhaps a config file that stores an array of values to save, and the default can be the bare minimum to load an image.

**Comment by aryehraber** [comment]
Hmm yeah, I did notice there's a lot of meta data returned by Unsplash 🤔 Been waiting for some feedback like this to decide on a course of action.

There's a few fields I definitely need to compile the `{{ splash:attribution }}` tag, but I guess the rest could be made optional. 

Will look into it, thanks @sebszocinski!

**Comment by aryehraber** [comment]
Hey @sebszocinski, this has been open for absolute ages, my apologies! 

With the release of Splash v2 which adds Statamic 4 support, I decided to also add this feature. Not sure if you're still using this addon in your projects, but hopefully this is useful anyway.
