### ISSUE TITLE
Problem selecting IMG

### ISSUE THREAD

**Issue by tobiasvielmetter** [aryehraber/statamic-splash#9]
Not sure if I am doing something wrong, but when I am trying to select an image it opens up larger in the background and the previously greyed out select button is hidden. Clicking again gets rid of the image in the background and the buttons return, but the image is unselected, so I cannot click select... with resizing the image the select button comes into view sometimes and I can actually select. Any tips about this, is it a bug? No JS error is triggered. See screenshot below. 
<img width="750" alt="Screenshot 2020-12-07 at 15 03 59" src="https://user-images.githubusercontent.com/5571166/101360531-0bddb700-389e-11eb-83a8-88f7d577fc55.png">

**Comment by aryehraber** [comment]
Hi @tobiasvielmetter, can you please confirm that you're on the latest version of Statamic & Splash?

**Comment by tobiasvielmetter** [comment]
Yes, I am on statamic 3.0.32 and just installed the plugin via composer. Anything else I can provide to debug? Thanks

**Comment by aryehraber** [comment]
Hmm, not sure... I just updated my local test project to latest Statamic, to ensure there wasn't a breaking change in a recent update, but everything seems to be working/looking fine here.

Can you try clear your browser cache to make sure the latest SplashFieldtype is getting loaded? You should see the following JS file get loaded in Network tab `splash-fieldtype.js`.

Also, can you please double check you're using Splash `v1.0.4` by running `composer info aryehraber/statamic-splash`. 

Thanks!

**Comment by tobiasvielmetter** [comment]
Yes, it does look like I am in the proper version and that I have the correct splash-fieldtype.js script. It might be browser related issue. I just tried in the current chrome version and it worked.  I've been trying this in Safari (current macOS Big Sur). Here is a screen-capture of the issue: https://drive.google.com/file/d/13tkPe5TvEKI2TXm6wB1Rk6pN7EUz6usS/view?usp=sharing

**Comment by aryehraber** [comment]
A-ha! Thanks for the extra details, am able to recreate the issue in Safari too!

Will try and push a fix sometime this week.

**Comment by tobiasvielmetter** [comment]
Great, thanks! :-)

**Comment by aryehraber** [comment]
Hi @tobiasvielmetter, sorry about the wait! This should now be fixed in latest release (`v1.0.5`), feel free to re-open if you continue experiencing the issue.
